### ISSUE TITLE
Rails 4.1 - cannot find compass

### ISSUE THREAD

**Issue by daveheitzman** [groundworkcss/groundworkcss-rails#16]
vanilla rails 4.1.9 newly generated app. 
followed instructions for groundwork. 

upon visiting any route I'm getting: 
 
 Showing /home/gruen/_code/ruby/test_groundwork/app/views/layouts/application.html.erb where line #5 raised:

File to import not found or unreadable: compass.
Load paths:
  /home/gruen/_code/ruby/test_groundwork/app/assets/images
  /home/gruen/_code/ruby/test_groundwork/app/assets/javascripts

... etc

**Comment by sepastian** [comment]
Same problem on rails 4.2!

```
$ bundle show
Gems included by the bundle:
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * compass-rails (1.1.6)
  * :
  * groundworkcss (2.3.5)
  * :
  * rails (4.2.0)
  * :
  * sass-rails (5.0.1)
  * :
```

**Comment by daveheitzman** [comment]
FYI - the solution, posted elsewhere as well, is to downgrade a couple of gems: 
gem 'rails', '4.1.8'
gem 'sass', '~> 3.2.0'
gem 'sass-rails', '~> 4.0.2'
gem 'compass-rails'

This is what I have and it's been working for me.

**Comment by sepastian** [comment]
Thanks @daveheitzman . But I need to use Rails 4.2. Will use bootstrap instead...

**Comment by ldewald** [comment]
I believe with the latest release (2.3.7), this has been fixed. Just tested in a fresh 4.1.9 app without issue.
