### ISSUE TITLE
Misunderstanding the install instructions

### ISSUE THREAD

**Issue by danwwilson** [groundworkcss/groundworkcss-rails#18]
Hi I'm new to Ruby on Rails and I am trying to get my head around how to use groundworkcss with Rails. I followed the instructions including gem lines in the gem file and `bundle install`. 

When I look in my `assets` folder it doesn't seem to have a groundwork folder. The only file that got created was a `_groundwork_settings.scss` file.

Have I missed something that tells me I needed to copy the files from the repository into my `assets` folder? Any guidance would be appreciated.
Thanks
Dan

**Comment by ghepting** [comment]
You should really take some time to understand how the [Rails asset pipeline](http://guides.rubyonrails.org/v4.0/asset_pipeline.html) works. Especially how gems utilize [Rails engines](http://api.rubyonrails.org/classes/Rails/Engine.html) to extend the functionality of a client application. Good luck!
